server:
  port: 7153

spring:
  application:
    name: dmw-base-consumer
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

#配置日志级别
logging:
  level:
    root: INFO
    com.szxs.mapper: DEBUG

