server:
  port: 7158

spring:
  rabbitmq:
    host: 192.168.6.150
    username: tys
    password: 111111
    virtual-host: /tys
    listener:
      direct:
        acknowledge-mode: manual
        prefetch: 1

  application:
    name: dmw-order-consumer
  redis:
    host: localhost
    port: 6379
    database: 15
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

#配置日志级别
logging:
  level:
    root: INFO
    com.szxs.mapper: DEBUG


