server:
  port: 7105

spring:
  application:
    name: dmw-scheduler-provider
  datasource:
    url: jdbc:mysql://localhost:3306/dm_scheduler?serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 111111
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

mybatis:
  type-aliases-package: com.szxs.entity
  mapper-locations: classpath:mapping/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#配置日志级别
logging:
  level:
    root: INFO
    com.szxs.mapper: DEBUG


