server:
  port: 7151

spring:
  application:
    name: dmw-item-consumer
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

  redis:
    host: localhost
    port: 6379
    database: 2

#配置日志级别
logging:
  level:
    root: INFO
    com.szxs.mapper: DEBUG

